development:
  adapter: postgresql
  encoding: unicode
  database: juice_backend_development
  host: localhost
  username: daddy
  password: gfhjkm123

test:
  adapter: postgresql
  encoding: unicode
  database: juice_backend_test
  host: localhost
  username: daddy
  password: gfhjkm123
